package com.proword.facade.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * @ClassName: WordUserPojo
 * @Description: 用户的pojo类
 * @author zhuweimin
 * @date 2017年9月27日 上午11:56:53
 *
 */
public class WordUserPojo implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 3944450601750812691L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column word_user.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column word_user.user_name
	 *
	 * @mbggenerated
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column word_user.user_password
	 *
	 * @mbggenerated
	 */
	private String userPassword;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column word_user.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column word_user.update_time
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column word_user.id
	 *
	 * @return the value of word_user.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column word_user.id
	 *
	 * @param id
	 *            the value for word_user.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column word_user.user_name
	 *
	 * @return the value of word_user.user_name
	 *
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column word_user.user_name
	 *
	 * @param userName
	 *            the value for word_user.user_name
	 *
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column word_user.user_password
	 *
	 * @return the value of word_user.user_password
	 *
	 * @mbggenerated
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column word_user.user_password
	 *
	 * @param userPassword
	 *            the value for word_user.user_password
	 *
	 * @mbggenerated
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column word_user.create_time
	 *
	 * @return the value of word_user.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column word_user.create_time
	 *
	 * @param createTime
	 *            the value for word_user.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column word_user.update_time
	 *
	 * @return the value of word_user.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column word_user.update_time
	 *
	 * @param updateTime
	 *            the value for word_user.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}
