package com.proword.service.BO;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * @ClassName: AdminUserBO
 * @Description: 管理员bo
 * @author zhuweimin
 * @date 2017年9月27日 上午10:38:01
 *
 */
public class AdminUserBO implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -4413914010789310719L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column admin_user.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column admin_user.admin_name
	 *
	 * @mbggenerated
	 */
	private String adminName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column admin_user.admin_password
	 *
	 * @mbggenerated
	 */
	private String adminPassword;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column admin_user.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column admin_user.update_time
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	private int pageSize;

	private int startSize;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column admin_user.id
	 *
	 * @return the value of admin_user.id
	 *
	 * @mbggenerated
	 */
	
	public Integer getId() {
		return id;
	}

	public int getPageSize() {
		return pageSize;
	}

	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}

	public int getStartSize() {
		return startSize;
	}

	public void setStartSize(int startSize) {
		this.startSize = startSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column admin_user.id
	 *
	 * @param id
	 *            the value for admin_user.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column admin_user.admin_name
	 *
	 * @return the value of admin_user.admin_name
	 *
	 * @mbggenerated
	 */
	public String getAdminName() {
		return adminName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column admin_user.admin_name
	 *
	 * @param adminName
	 *            the value for admin_user.admin_name
	 *
	 * @mbggenerated
	 */
	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column admin_user.admin_password
	 *
	 * @return the value of admin_user.admin_password
	 *
	 * @mbggenerated
	 */
	public String getAdminPassword() {
		return adminPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column admin_user.admin_password
	 *
	 * @param adminPassword
	 *            the value for admin_user.admin_password
	 *
	 * @mbggenerated
	 */
	public void setAdminPassword(String adminPassword) {
		this.adminPassword = adminPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column admin_user.create_time
	 *
	 * @return the value of admin_user.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column admin_user.create_time
	 *
	 * @param createTime
	 *            the value for admin_user.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column admin_user.update_time
	 *
	 * @return the value of admin_user.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column admin_user.update_time
	 *
	 * @param updateTime
	 *            the value for admin_user.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public void checkAdminUser() {
		if (adminName == null || adminPassword == null) {
			throw new RuntimeException("管理员名字或者密码不能为空，操作失败");
		}
	}

	public void checkId() {
		if(id == null) {
			throw new RuntimeException("id不能为空，操作失败");
		}
	}
}
