package com.proword.service.BO;

import java.io.Serializable;
import java.util.Date;

public class WordDataBO implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4672336937904928175L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_data.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_data.group_word
     *
     * @mbggenerated
     */
    private String groupWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_data.back_color
     *
     * @mbggenerated
     */
    private String backColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_data.front_color
     *
     * @mbggenerated
     */
    private String frontColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_data.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_data.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_data.id
     *
     * @return the value of word_data.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_data.id
     *
     * @param id the value for word_data.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_data.group_word
     *
     * @return the value of word_data.group_word
     *
     * @mbggenerated
     */
    public String getGroupWord() {
        return groupWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_data.group_word
     *
     * @param groupWord the value for word_data.group_word
     *
     * @mbggenerated
     */
    public void setGroupWord(String groupWord) {
        this.groupWord = groupWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_data.back_color
     *
     * @return the value of word_data.back_color
     *
     * @mbggenerated
     */
    public String getBackColor() {
        return backColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_data.back_color
     *
     * @param backColor the value for word_data.back_color
     *
     * @mbggenerated
     */
    public void setBackColor(String backColor) {
        this.backColor = backColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_data.front_color
     *
     * @return the value of word_data.front_color
     *
     * @mbggenerated
     */
    public String getFrontColor() {
        return frontColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_data.front_color
     *
     * @param frontColor the value for word_data.front_color
     *
     * @mbggenerated
     */
    public void setFrontColor(String frontColor) {
        this.frontColor = frontColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_data.create_time
     *
     * @return the value of word_data.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_data.create_time
     *
     * @param createTime the value for word_data.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_data.update_time
     *
     * @return the value of word_data.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_data.update_time
     *
     * @param updateTime the value for word_data.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public void checkWordData() {
		if(null==groupWord) {
			new Exception("参数不全！");
		}
		
	}
}