package com.proword.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WordDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_data
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_data
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_data
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public WordDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_data
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGroupWordIsNull() {
            addCriterion("group_word is null");
            return (Criteria) this;
        }

        public Criteria andGroupWordIsNotNull() {
            addCriterion("group_word is not null");
            return (Criteria) this;
        }

        public Criteria andGroupWordEqualTo(String value) {
            addCriterion("group_word =", value, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordNotEqualTo(String value) {
            addCriterion("group_word <>", value, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordGreaterThan(String value) {
            addCriterion("group_word >", value, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordGreaterThanOrEqualTo(String value) {
            addCriterion("group_word >=", value, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordLessThan(String value) {
            addCriterion("group_word <", value, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordLessThanOrEqualTo(String value) {
            addCriterion("group_word <=", value, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordLike(String value) {
            addCriterion("group_word like", value, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordNotLike(String value) {
            addCriterion("group_word not like", value, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordIn(List<String> values) {
            addCriterion("group_word in", values, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordNotIn(List<String> values) {
            addCriterion("group_word not in", values, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordBetween(String value1, String value2) {
            addCriterion("group_word between", value1, value2, "groupWord");
            return (Criteria) this;
        }

        public Criteria andGroupWordNotBetween(String value1, String value2) {
            addCriterion("group_word not between", value1, value2, "groupWord");
            return (Criteria) this;
        }

        public Criteria andBackColorIsNull() {
            addCriterion("back_color is null");
            return (Criteria) this;
        }

        public Criteria andBackColorIsNotNull() {
            addCriterion("back_color is not null");
            return (Criteria) this;
        }

        public Criteria andBackColorEqualTo(String value) {
            addCriterion("back_color =", value, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorNotEqualTo(String value) {
            addCriterion("back_color <>", value, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorGreaterThan(String value) {
            addCriterion("back_color >", value, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorGreaterThanOrEqualTo(String value) {
            addCriterion("back_color >=", value, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorLessThan(String value) {
            addCriterion("back_color <", value, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorLessThanOrEqualTo(String value) {
            addCriterion("back_color <=", value, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorLike(String value) {
            addCriterion("back_color like", value, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorNotLike(String value) {
            addCriterion("back_color not like", value, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorIn(List<String> values) {
            addCriterion("back_color in", values, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorNotIn(List<String> values) {
            addCriterion("back_color not in", values, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorBetween(String value1, String value2) {
            addCriterion("back_color between", value1, value2, "backColor");
            return (Criteria) this;
        }

        public Criteria andBackColorNotBetween(String value1, String value2) {
            addCriterion("back_color not between", value1, value2, "backColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorIsNull() {
            addCriterion("front_color is null");
            return (Criteria) this;
        }

        public Criteria andFrontColorIsNotNull() {
            addCriterion("front_color is not null");
            return (Criteria) this;
        }

        public Criteria andFrontColorEqualTo(String value) {
            addCriterion("front_color =", value, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorNotEqualTo(String value) {
            addCriterion("front_color <>", value, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorGreaterThan(String value) {
            addCriterion("front_color >", value, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorGreaterThanOrEqualTo(String value) {
            addCriterion("front_color >=", value, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorLessThan(String value) {
            addCriterion("front_color <", value, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorLessThanOrEqualTo(String value) {
            addCriterion("front_color <=", value, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorLike(String value) {
            addCriterion("front_color like", value, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorNotLike(String value) {
            addCriterion("front_color not like", value, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorIn(List<String> values) {
            addCriterion("front_color in", values, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorNotIn(List<String> values) {
            addCriterion("front_color not in", values, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorBetween(String value1, String value2) {
            addCriterion("front_color between", value1, value2, "frontColor");
            return (Criteria) this;
        }

        public Criteria andFrontColorNotBetween(String value1, String value2) {
            addCriterion("front_color not between", value1, value2, "frontColor");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andWordTypeIsNull() {
            addCriterion("word_type is null");
            return (Criteria) this;
        }

        public Criteria andWordTypeIsNotNull() {
            addCriterion("word_type is not null");
            return (Criteria) this;
        }

        public Criteria andWordTypeEqualTo(String value) {
            addCriterion("word_type =", value, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeNotEqualTo(String value) {
            addCriterion("word_type <>", value, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeGreaterThan(String value) {
            addCriterion("word_type >", value, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeGreaterThanOrEqualTo(String value) {
            addCriterion("word_type >=", value, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeLessThan(String value) {
            addCriterion("word_type <", value, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeLessThanOrEqualTo(String value) {
            addCriterion("word_type <=", value, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeLike(String value) {
            addCriterion("word_type like", value, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeNotLike(String value) {
            addCriterion("word_type not like", value, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeIn(List<String> values) {
            addCriterion("word_type in", values, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeNotIn(List<String> values) {
            addCriterion("word_type not in", values, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeBetween(String value1, String value2) {
            addCriterion("word_type between", value1, value2, "wordType");
            return (Criteria) this;
        }

        public Criteria andWordTypeNotBetween(String value1, String value2) {
            addCriterion("word_type not between", value1, value2, "wordType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_data
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_data
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}