package com.proword.mapper;

import com.proword.model.WordData;
import com.proword.model.WordDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    int countByExample(WordDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    int deleteByExample(WordDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    int insert(WordData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    int insertSelective(WordData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    List<WordData> selectByExample(WordDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    WordData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WordData record, @Param("example") WordDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WordData record, @Param("example") WordDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WordData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WordData record);
}