package com.proword.mapper;

import com.proword.model.WordDict;
import com.proword.model.WordDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    int countByExample(WordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    int deleteByExample(WordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    int insert(WordDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    int insertSelective(WordDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    List<WordDict> selectByExample(WordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    WordDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WordDict record, @Param("example") WordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WordDict record, @Param("example") WordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WordDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WordDict record);
}