package com.proword.mapper;

import com.proword.model.WordUser;
import com.proword.model.WordUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    int countByExample(WordUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    int deleteByExample(WordUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    int insert(WordUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    int insertSelective(WordUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    List<WordUser> selectByExample(WordUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    WordUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WordUser record, @Param("example") WordUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WordUser record, @Param("example") WordUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WordUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WordUser record);
}